name: manager_app
description: FleetFuel360 Companies - Fleet management for owners and managers
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  fleetfuel_core:
    path: ../../packages/fleetfuel_core

  firebase_core: ^3.6.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.6
  google_sign_in: ^6.2.1

  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  go_router: ^14.2.7

  google_maps_flutter: ^2.7.0
  geolocator: ^12.0.0
  cached_network_image: ^3.3.1
  photo_view: ^0.15.0

  fl_chart: ^0.69.0
  timeline_tile: ^2.0.0

  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  intl: ^0.19.0
  connectivity_plus: ^6.0.5
  permission_handler: ^11.3.1
  uuid: ^4.4.0
  package_info_plus: ^8.0.2
  url_launcher: ^6.3.0
  share_plus: ^12.0.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  riverpod_generator: ^2.3.5
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
